### ISSUE TITLE
where is p2bb_v5.pkl from?

### ISSUE THREAD

**Issue by undcloud** [aaxwaz/Humpback-whale-identification-challenge#4]
hello, there is no  description about it  ,  so could you tell me:   
is it annotation by human ?    
or is it a model prediction?  
@ZFTurbo @aaxwaz

**Comment by ZFTurbo** [comment]
It's the file with bounding boxes for each whale image, ensembled from 2 models as I remember. You can get it here:
https://www.dropbox.com/s/dszv34fi8wk1jvf/p2bb_v5.pkl?dl=1

**Comment by undcloud** [comment]
thank you very much ~
